# Generated by Django 3.0.5 on 2021-04-15 06:48

import django.core.validators
from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pics')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('qly', models.CharField(max_length=30)),
                ('exp', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('filepath', models.FileField(upload_to='files', validators=[school.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.doc', 'pdf', '.docx'])], verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('clas', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
            ],
        ),
    ]
