# Generated by Django 3.0.5 on 2021-04-15 06:58

import django.core.validators
from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='filepath',
            field=models.FileField(upload_to='', validators=[school.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['.doc', 'pdf', '.docx'])], verbose_name=''),
        ),
    ]
